### ISSUE TITLE
Rename variable font

### ISSUE THREAD

**Issue by RosaWagner** [jeremymickel/RedHatFonts#14]
We will just send the variable font to GF and it must not contain `VF` in it.

It would make things easier if all formats were build from the same sources (VF, but named without VF), and eventually the statics could contain TT / OT in it to allow people to install the fonts from this repo on the same machine. You can use the script `gftools rename-font` in your build script to do so.

**Comment by jeremymickel** [comment]
There is now a Variable Font option without VF in the name.
