### ISSUE TITLE
Support for PANOSE

### ISSUE THREAD

**Issue by jeremymickel** [jeremymickel/RedHatFonts#2]
Fontbakery is reporting a FAIL for Panose being mismatched between Proportional and Mono fonts

`🔥 FAIL PANOSE proportion is not the same across this family. In order to fix this, please make sure that the panose.bProportion value is the same in the OS/2 table of all of this family font files. [code: inconsistency]`

Fontbakery also reports a FAIL for Monospace Panose not being correct. When I open the TTF / OTF files, Panose is not included. Let's include in the build script.

`🔥 FAIL On monospaced fonts, the value of OS/2.panose.bProportion must be set to 9 (proportion: monospaced), but got 0 instead. [code: mono-bad-panose-proportion]`

**Comment by bghryct** [comment]
https://github.com/jeremymickel/RedHatFonts/pull/10

Should close this issue.
