### ISSUE TITLE
Build script is adding Windows (but not Mac) Name Records

### ISSUE THREAD

**Issue by jeremymickel** [jeremymickel/RedHatFonts#5]
This is causing an error in `afdko comparefamily`

```
	Error: Missing Mac Postcriptname from name table! Should be in record (1, 0, 0, 6)
	Error: Missing Mac Compatible Family Name from name table! Should be in record (1, 0, 0, 1) 
	Error: Missing Mac Compatible SubFamily Name from name table! Should be in record (1, 0, 0, 2) 
	Error: Missing Mac Full Font Name from name table! Should be in record (1, 0, 0, 4) 
	Warning: Missing Mac Version String from name table! Should be in record (1, 0, 0, 5) 

Error: The  Mac and Windows Compatible Names for the regular face of a style-linked group should be the same. Font 
	Mac Compatible Name: 
	Windows Compatible Name: Red Hat Display

```

<img width="543" alt="Screen Shot 2021-02-10 at 6 48 51 PM" src="https://user-images.githubusercontent.com/2964496/107597839-bd67d400-6bd0-11eb-981d-2682885f2b0c.png">

**Comment by bghryct** [comment]
https://github.com/googlefonts/fontmake/issues/360

Appears to be an open debate, around how fontmake handles building name tables. A solution could be using the FDK process, but that would entail significant reworking of the directory structures of this project. 

That being said, as we've discussed that process has a history of producing less error prone otfs. Whether or not many of the old 'solutions' are still necessary seems to be an ongoing discussion.

**Comment by frankrolf** [comment]
FWIW (and I am fully aware I am commenting on a 2-year-old, closed issue) — none of the latest Adobe fonts include Mac name IDs . `comparefamily`’s output should always be taken as an opinion, not the absolute truth.
