### ISSUE TITLE
Working names / final names?

### ISSUE THREAD

**Issue by jeremymickel** [jeremymickel/RedHatFonts#6]
I've previously used a GOADB file to resolve working / final names for characters like Kcommaaccent.

Possible to reference a GOADB file for this workflow?

example:

```
uni0136	Kcommaaccent	uni0136
Lacute	Lacute	uni0139
Lcaron	Lcaron	uni013D
uni013B	Lcommaaccent	uni013B
Ldot	Ldot	uni013F
Lslash	Lslash	uni0141
Nacute	Nacute	uni0143
Ncaron	Ncaron	uni0147
uni0145	Ncommaaccent	uni0145

```

**Comment by bghryct** [comment]
Per our discussion this is safe at least according to FB. 

Fraunces build doesn't seem to require a GOADB, and as such it is also probably unnecessary here.
